name: Save PR Data per PR

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  save_pr_data:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # PR情報を取得して保存
      - name: Save PR data locally
        id: save_pr_data
        run: |
          # ディレクトリ作成
          mkdir -p $GITHUB_WORKSPACE/pr_data

          # 環境変数でPR番号を取得
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # JSON形式でデータを保存（PR番号ごとにファイルを分割）
          echo "${{ toJson(github.event) }}" > "$GITHUB_WORKSPACE/pr_data/pr_${PR_NUMBER}.json"

          # 保存したファイルの確認
          echo "Saved PR data for PR #${PR_NUMBER} as pr_${PR_NUMBER}.json"
          ls -la $GITHUB_WORKSPACE/pr_data

      # 保存したデータを確認
      - name: Display saved PR data
        run: |
          for file in $GITHUB_WORKSPACE/pr_data/*.json; do
            echo "Content of $file:"
            cat $file
          done
