name: Save PR Data per PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  save_pr_data:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. PR情報を取得して保存
      - name: Save PR data locally
        run: |
          set -e  # エラー時にスクリプトを停止
          mkdir -p pr_data
          PR_NUMBER="${{ github.event.pull_request.number }}"
          EVENT_TYPE="${{ github.event.action }}"
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)

          # JSONデータをファイルに保存
          echo '${{ toJson(github.event) }}' | jq '.' > "pr_data/pr_${PR_NUMBER}_${EVENT_TYPE}_${TIMESTAMP}.json"

          echo "PR data saved successfully."

      # 3. GitHub Artifacts にアップロード
      - name: Upload PR data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_data
          path: pr_data

      # 4. `pr-data` ブランチに保存 (同じリポジトリに強制プッシュ)
      - name: Push PR data to pr-data branch
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin
          git checkout -b pr-data || git checkout pr-data
          cp -r pr_data/* .
          git add pr_data
          git commit -m "Add PR data for PR #${PR_NUMBER} - ${EVENT_TYPE} at ${TIMESTAMP}"
          git push --force origin pr-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
