name: Save PR Data Locally

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  save_pr_data:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # PR情報をローカルに保存
      - name: Save PR data locally
        id: save_pr_data
        run: |
          # GitHub Actionsのワークスペース内に保存用ディレクトリを作成
          mkdir -p $GITHUB_WORKSPACE/pr_data

          # PR番号とイベントタイプを取得
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # JSONデータを保存
          echo "${{ toJson(github.event) }}" > "$GITHUB_WORKSPACE/pr_data/pr_${PR_NUMBER}.json"

          # 保存したファイルを表示
          ls -la $GITHUB_WORKSPACE/pr_data

      # 保存されたファイルを確認
      - name: Display saved PR data
        run: |
          cat $GITHUB_WORKSPACE/pr_data/*.json
