name: Save PR Data per PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  save_pr_data:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. `pr-data` ブランチを取得（なければ作成）
      - name: Fetch or create pr-data branch
        run: |
          git fetch origin
          git checkout -b pr-data || git checkout pr-data
          git pull --rebase origin pr-data || echo "Branch pr-data does not exist yet."

      # 3. PR情報を取得して保存
      - name: Save PR data locally
        run: |
          set -e  # エラー時にスクリプトを停止
          mkdir -p pr_data
          PR_NUMBER="${{ github.event.pull_request.number }}"
          EVENT_TYPE="${{ github.event.action }}"
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          FILE_PATH="pr_data/pr_${PR_NUMBER}_${EVENT_TYPE}_${TIMESTAMP}.json"

          # JSONデータをファイルに追加（既存データは保持）
          echo '${{ toJson(github.event) }}' | jq '.' > "$FILE_PATH"

          echo "PR data saved successfully: $FILE_PATH"

      # 4. GitHub Artifacts にアップロード
      - name: Upload PR data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_data
          path: pr_data

      # 5. `pr-data` ブランチに新規ファイルを追加（削除せずに保持）
      - name: Push PR data to pr-data branch
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # `pr_data` ディレクトリ内の新しいデータを追加
          git add pr_data
          git commit -m "Add PR data for PR #${{ github.event.pull_request.number }} - ${{ github.event.action }} at $(date +%Y-%m-%d_%H:%M:%S)"
          git push origin pr-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
