name: Train Model with PR Data

on:
  schedule:
    - cron: "0 15 * * *"  # 毎日 15:00 UTC (日本時間 24:00) に実行
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull PR data from main branch
        run: |
          git fetch origin main || echo "No main branch found"
          git checkout main
          git pull --rebase --autostash origin main || (echo "Rebase failed, resolving manually" && git rebase --abort && git reset --hard origin/main)
          mkdir -p pr_data
          cp -r pr_data/* pr_data/ || echo "No PR data found."

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: |
          if [ -d "pr_data" ]; then
            python scripts/train.py
          else
            echo "No PR data available. Skipping training."
            exit 1
          fi

      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/balanced_random_forest_model.pkl

      - name: Push trained model to main branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          cp models/balanced_random_forest_model.pkl .
          git checkout main
          git pull --rebase --autostash origin main  # ✅ 修正: autostash を追加
          git add balanced_random_forest_model.pkl
          git commit -m "Update trained model on PR" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
